### PR TITLE
Add a dartdoc verify action in GitHub Actions

### PR DESCRIPTION
**Pull request by srawlins**

### CODE REVIEW

**Comment by srawlins** [comment]
CC @athomas @devoncarew This is the result of my experiment to validate docs.

**Review by jcollins-g — APPROVED** [review]
Not an expert yet on github actions, but the dartdoc piece definitely looks good to me.

Filed dart-lang/dartdoc#2504 as the flag to set broken-link as an error doesn't seem to take effect here for some reason.

**Comment by srawlins** [comment]
CC @kevmoo I thought you might be interested in this idea too

**Comment by kevmoo** [comment]
We need to put this in a bottle!

Maybe something built off https://github.com/dart-lang/setup-dart – 

CC @mit-mit @athomas

**Comment by mit-mit** [comment]
Rather than adding a complex command like that in setup-dart, I'd much rather get it into `dart` as something like `dart doc --dry-run`.

**Pull request merged**
