### PR TITLE
Lints

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by srawlins** [comment]
Mockito is now google3-first. I can set up a workflow to accept PRs, but it's tricky. Do you mind if I take this PR, copy it to google3, and submit it there, before syncing back to GitHub?

**Comment by kevmoo** [comment]
Sure!

**Comment by kevmoo** [comment]
Er, sadly I don't have a linux box set up.

What are my options?

**Comment by srawlins** [comment]
No problem; I synced it internally. This will get pushed out to GitHub soon.

**Pull request closed without merging**
