### PR TITLE
fix(linter): ignore some linters triggered by generated files

### PR DESCRIPTION
**Pull request by jhionan**
Some generated code is triggering some linters making pipelines with this linters to fail.
Generated files should not trigger any linter.

image

### CODE REVIEW

**Comment by srawlins** [comment]
Thanks for the PR.

It is unsustainable to add an ignore line for every lint rule. I've added the common ones and the ones rules used by `lints` and `flutter_lints`, but probably will not add any for other rules.

* always_specify_types - Is this rule recommended somewhere?
* unnecessary_overrides - mockito should not be generating unnecessary overrides. I have a change in flight that fixes #461 differently.
* implementation_imports - This is already ignored on line 88.
* avoid_implementing_value_types - Is this rule recommended somewhere?

**Comment by jhionan** [comment]
avoid_implementing_value_types: was recommended on dart, but they removed this rule when moving to null safety

**Comment by jhionan** [comment]
removed the duplicate `implementation_imports` entry

**Comment by jhionan** [comment]
I'll drop this got the conclusion that the best solution is excluding mocks from anyproject analyzer
```
exclude:
    - "**/*.mocks.dart"
```

**Comment by srawlins** [comment]
Haha sorry about that. I think that's a fine solution for now. In the future we will `// ignore_for_file: type=lint`.

**Pull request closed without merging**
