### PR TITLE
GitHub Sync

### PR DESCRIPTION
**Pull request by srawlins**
This is an automatically generated pull request.

### CODE REVIEW

**Comment by srawlins** [comment]
Travis appears to be... asleep?

**Comment by natebosch** [comment]
> Travis appears to be... asleep?

It's been getting less and less reliable. Probably time to switch this repo to github actions.

**Comment by srawlins** [comment]
@athomas Travis has been stuck on this PR for a few days (with new commits mailed up). Is mockito on your list to migrate to GitHub Actions soon?

**Comment by srawlins** [comment]
This is ready for review now, @natebosch

**Review by natebosch — APPROVED** [review]

**Comment by athomas** [comment]
@srawlins this mostly reverted #328 (except for the deletion of `.travis.yml`).

**Comment by srawlins** [comment]
Oops, I'll fix that on the next sync, today I think.

**Pull request merged**
