### PR TITLE
Relax mixin criteria

### LINKED ISSUE #603: Generating mocks mixing in `MockPlatformInterfaceMixin`
Automatic mock generation currently requires that mixins implement the type being mocked, which precludes mixins like [`MockPlatformInterfaceMixin`](https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/MockPlatformInterfaceMixin-class.html).

Simply removing the check seems to produce no ill effects for me:
```diff
       }
       final mixinInterfaceType =
           _determineDartType(typeToMixin, entryLib.typeProvider);
-      if (!mixinInterfaceType.interfaces.contains(type)) {
-        throw InvalidMockitoAnnotationException('The "mixingIn" type, '
-            '${typeToMixin.getDisplayString(withNullability: false)}, must '
-            'implement the class to mock, ${typeToMock.getDisplayString(withNullability: false)}');
-      }
       mixins.add(mixinInterfaceType);
     }
```
https://github.com/AsturaPhoenix/mockito/commit/9d36e917de6d4bc004abda2ee2b54f9b31ab4fb2

Example usage:
```dart
@GenerateNiceMocks([
  MockSpec<TripPlannerHttpClient>(),
  MockSpec<http.Client>(),
  MockSpec<PermissionHandlerPlatform>(mixingIn: [MockPlatformInterfaceMixin]),
  MockSpec<GeolocatorPlatform>(mixingIn: [MockPlatformInterfaceMixin]),
])
import 'harness.mocks.dart';
```
https://github.com/AsturaPhoenix/trip_planner_aquamarine/blob/6f1356e2b7d82a817f0dabb63aff1fe686c19275/test/util/harness.dart#L24-L25

Is there a story behind this? I'd be open to doing further investigation and a short pull request.

### PR DESCRIPTION
**Pull request by AsturaPhoenix**
Remove the restriction that mixins must implement the mocked type so that [MockPlatformInterfaceMixin](https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/MockPlatformInterfaceMixin-class.html) can be used.

Fixes #603

### CODE REVIEW

**Review by yanok — APPROVED** [review]
lgtm

**Comment by srawlins** [comment]
That is a strange CI failure...

**Comment by AsturaPhoenix** [comment]
Repros for me locally on dart-sdk dev as well. Investigating further; I suspect it's a dart regression, but the dart/sdk actions look green at first glance.

**Comment by srawlins** [comment]
@kevmoo did just bump `build_web_compilers`, which may have something to do with it. https://github.com/dart-lang/mockito/commit/d2a8df169706d1c1e5daaf0c96ee03b8238bd599

**Comment by kevmoo** [comment]
@jakemac53 and @nshahan did the BWC work, me thinks

**Comment by kevmoo** [comment]
> @jakemac53 and @nshahan did the BWC work, me thinks

Nope. Sorry. I bumped the lower bound here.

**Comment by jakemac53** [comment]
If you look at the pub solve it wasn't able to get the latest build_web_compilers - so that is why its failing.

**Comment by jakemac53** [comment]
I think maybe this PR just needs to be synced with master?

**Pull request merged**
